

SET NAMES utf8mb4;
SET time_zone = "+03:00";

CREATE TABLE IF NOT EXISTS clinics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_ar VARCHAR(120) NOT NULL,
  name_en VARCHAR(120) NOT NULL,
  area_ar VARCHAR(180) NOT NULL,
  area_en VARCHAR(180) NOT NULL,
  days_ar VARCHAR(120) NOT NULL,
  days_en VARCHAR(120) NOT NULL,
  hours_ar VARCHAR(120) NOT NULL,
  hours_en VARCHAR(120) NOT NULL,
  phone VARCHAR(32) NULL,
  maps_url TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emergency_info (
  id INT AUTO_INCREMENT PRIMARY KEY,
  location_ar VARCHAR(180) NOT NULL,
  location_en VARCHAR(180) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  maps_url TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pharmacy_info (
  id INT AUTO_INCREMENT PRIMARY KEY,
  location_ar VARCHAR(180) NOT NULL,
  location_en VARCHAR(180) NOT NULL,
  hours_ar VARCHAR(180) NOT NULL,
  hours_en VARCHAR(180) NOT NULL,
  phone VARCHAR(32) NULL,
  maps_url TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visiting_hours (
  id INT AUTO_INCREMENT PRIMARY KEY,
  info_ar VARCHAR(220) NOT NULL,
  info_en VARCHAR(220) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_ar VARCHAR(160) NOT NULL,
  name_en VARCHAR(160) NOT NULL,
  description_ar TEXT NOT NULL,
  description_en TEXT NOT NULL,
  phone VARCHAR(32) NULL,
  location_ar VARCHAR(180) NOT NULL,
  location_en VARCHAR(180) NOT NULL,
  hours_ar VARCHAR(180) NOT NULL,
  hours_en VARCHAR(180) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faqs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  q_ar VARCHAR(255) NOT NULL,
  a_ar TEXT NOT NULL,
  q_en VARCHAR(255) NOT NULL,
  a_en TEXT NOT NULL,
  tags VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;